name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use NodeJS 18
      uses: actions/setup-node@v4
      with:
        node-version: '18.16.0'
        cache: 'yarn'
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Setup npm
      run: |
        npm set @apostroxyz:registry=https://registry.npmjs.org/
        npm set "//registry.npmjs.org/:_authToken=${NPM_TOKEN}"

    - name: Setup git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"

    - name: Prepare yarn
      run: |
        yarn install --immutable

    - name: Build packages
      run: |
        yarn build

    - name: Version and publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ ${{ github.base_ref }} = development ]; then
          yarn lerna publish --conventional-commits --conventional-prerelease --create-release github --loglevel debug --yes
        else
          yarn lerna publish --conventional-commits --conventional-graduate --create-release github --loglevel debug --yes
